### ISSUE TITLE
crawler

### ISSUE THREAD

**Issue by vulnz** [Hack-Hut/CrabStick#1]
hello bro!
please don't leave project ;)
make crawler

**Comment by Hack-Hut** [comment]
Thinking of re-doing the project, now that I'm a better programmer.

**Comment by vulnz** [comment]
please do crawler bro

**Comment by Sydwicked** [comment]
> Thinking of re-doing the project, now that I'm a better programmer.

Keep doing what you do best and hope to see an update. Thanx a lot for the program.

**Comment by Hack-Hut** [comment]
Fuck it, i'm going to re write the whole thing. I wanted to add multi-threading as well but there is no way that I will be able to do that with out some major changes anyway.

**Comment by Sydwicked** [comment]
Do it at your own pace, I believe in you to succeed.

**Comment by Sydwicked** [comment]
> Fuck it, i'm going to re write the whole thing. I wanted to add multi-threading as well but there is no way that I will be able to do that with out some major changes anyway.

Can this program run on pages that don't have php extension?

**Comment by Hack-Hut** [comment]
Main sites that effected are php and jsp based sites. Although if the web server has server side includes this can also make the site vulnerable.

**Comment by Hack-Hut** [comment]
Crawler in process of making, closing the thread
